### ISSUE TITLE
Práctica 

### ISSUE THREAD

**Issue by Paola939** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Paola939#1]
[Practica_Paola Rosario Ayala.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-Paola939/files/12571071/Practica_Paola.Rosario.Ayala.pdf)

**Comment by Felix-Angel** [comment]
PORTADA 25%
PROCEDIMIENTO (FALTA DE OBJETIVOS DE LA PRACTICA) 22%
FIGURAS ILUSTRACIONES Y FOTOGRAFÍAS 25%
RESULTADOS Y CONCLUSIONES 25%
CALIFICACION:  97/100
CALIFICADO POR : "EQUIPO DE MAYRA, DIEGO, DANIEL, FELIX"

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
